variables:
  DOCKER_USER: ci
  AWS_REGION: ap-southeast-2
  AWS_ACCOUNT: 814504268053
  BUILD_ENV: production

before_script:
  - touch .env
  - make --version
  - aws --version
  - terraform --version
  - docker --version

stages:
  - build
  - upload
  - deploy

tf:plan:
  tags:
    - linode
  stage: build
  script:
    - make plan
  only:
    refs:
      - merge_request
      - main
  artifacts:
    name: tfplan
    paths:
      - plans/.tfplan
    reports:
      terraform: plans/tfplan.json

build:ingress:
  tags:
    - linode
  stage: build
  script:
    - make docker-login
    - ./bin/gen_cert
    - make build-ci-ingress
  only:
    refs:
      - merge_request
      - main

build:certbot:
  tags:
    - linode
  stage: build
  script:
    - make docker-login
    - make build-ci-certbot
  only:
    refs:
      - merge_request
      - main

tf:apply:
  tags:
    - linode
  stage: deploy
  script:
    - make apply
  only:
    refs:
      - main
  environment:
    name: linode
    url: https://cloud.linode.com/search/?query=label:ingress-controller
    on_stop: tf:destroy
  dependencies:
    - tf:plan
  when: manual

tf:destroy:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  tags:
    - linode
  script:
    - make destroy
  when: manual
  environment:
    name: linode
    action: stop
  artifacts:
    name: tfdestroy
    paths:
      - plans/.tfdestroy
    reports:
      terraform: plans/tfdestroy.json

push:docker:
  tags:
    - linode
  stage: deploy
  script:
    - make docker-login
    - make push-ci
  only:
    refs:
      - main
