version: '3.7'
x-defaults: &defaults
  logging:
    options:
      max-size: "10m"
      max-file: "3"

services:
  ingress:
    <<: *defaults
    image: "registry.gitlab.com/trivialsec/ingress-controller/nginx:${IMAGE_TAG}"
    container_name: ingress-controller
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 80
      - 443
    volumes:
      - .${BUILD_ENV}/nginx.conf:/etc/nginx/nginx.conf
      - .${BUILD_ENV}/conf.d:/etc/nginx/conf.d
      - .${BUILD_ENV}/certs:/etc/nginx/certs
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
      - NET_BIND_SERVICE
    networks:
      default:
        aliases:
          - nginx
          - ingress
          - waf
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
      resources:
        limits:
          cpus: '1.00'
          memory: 1GB
        reservations:
          memory: 500M

networks:
  default:
    external:
      name: trivialsec
