#!/usr/bin/env bash
set -ex

if ! [ -f /tmp/domains.txt ]; then
  echo "/tmp/domains.txt not found, exiting..."
  exit 0
fi
declare -a domains=($(cat /tmp/domains.txt))
readonly rsa_key_size=4096

for domain in "${domains[@]}"; do
  path="/etc/letsencrypt/live/${domain}"
  mkdir -p ${path}
  echo "Generating rsa:${rsa_key_size} x509 certificate for ${domain}"
  # Create the certificate key
  openssl genrsa -out ${path}/privkey.pem ${rsa_key_size}
  # Create the signing (csr)
  openssl req -new -sha256 \
    -key ${path}/privkey.pem \
    -subj "/C=AU/O=Trivial Security/OU=Trivial Security/CN=${domain}" \
    -out ${path}/root.csr
  # Verify the csr's content
  openssl req -in ${path}/root.csr -noout -text
  # Generate the certificate using the root.csr and privkey.pem with the CA Root key
  openssl x509 -req \
    -in ${path}/root.csr \
    -CA /tmp/rootCA.crt \
    -CAkey /tmp/rootCA.pem \
    -CAcreateserial \
    -extfile <(cat /tmp/v3.ext \
        <(printf "DNS.1 = ${domain}")) \
    -out ${path}/fullchain.pem \
    -days 30 -sha256
  # Verify the certificate
  openssl x509 -in ${path}/fullchain.pem -text -noout

done

rm /tmp/rootCA.pem

trap exit TERM
while :; do
  sleep 10m &
  wait $!
  nginx -s reload
done &

exec $@
